---
name: SignShop
main: SignShop\SignShop
version: [3.0.1]
api: [3.0.0]
load: POSTWORLD
author: xionbig
description: "Buy and Sell the items using Signs with virtual-money."
permissions:
 sign:
  default: notop
  description: "Allows do all that SignShop"
  children:
   sign.command:
    default: true
    description: "Allows using all the SignShop commands"
